/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";
import { useGarageStore } from "@/store/useGarageStore";

export default function SM6_Body({ ...props }: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=SM6/SM6_body.glb") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.SM6_Body_Base1_1.geometry} material={materials.metal} />
        <mesh geometry={nodes.SM6_Body_Base1_2.geometry} material={materials.out_black} />
        <mesh geometry={nodes.SM6_Body_Base1_3.geometry} material={materials.shade} />
        <mesh geometry={nodes.SM6_Body_Base1_4.geometry} material={materials.plastic_gloss} />
        <mesh geometry={nodes.SM6_Body_Base1_5.geometry} material={materials.Silver} />
        <mesh geometry={nodes.SM6_Body_Base1_6.geometry} material={materials.glass} />
        <mesh geometry={nodes.SM6_Body_Base1_7.geometry} material={materials.mirror} />
      </group>
      <mesh geometry={nodes.SM6_Body_Base0_1.geometry} material={materials.Silver} />
      <mesh geometry={nodes.SM6_Body_Base0_2.geometry} material={materials.chrome_black} />
      <mesh
        geometry={nodes.SM6_Body_Base0_3.geometry}
        material={materials.main}
        material-color={selectedColors.Body}
        material-metalness={0.05}
        material-roughness={0.15}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=SM6/SM6_body.glb");
