/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";
import { useGarageStore } from "@/store/useGarageStore";

export default function QM6_Spoiler_Offroad(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=QM6/QM6_spoiler.glb?1") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group {...props}>
      <mesh castShadow receiveShadow geometry={nodes.QM6_Spoiler_Offroad_1.geometry} material={materials.Color_R} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_Spoiler_Offroad_2.geometry}
        material={materials.main}
        material-color={selectedColors.Spoiler}
      />
      <mesh castShadow receiveShadow geometry={nodes.QM6_Spoiler_Offroad_3.geometry} material={materials.metal} />
      <mesh castShadow receiveShadow geometry={nodes.QM6_Spoiler_Offroad_4.geometry} material={materials.out_black} />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=QM6/QM6_spoiler.glb?1");
