/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React from "react";
import { useGLTF } from "@react-three/drei";

export default function QM6_Spoiler_Futuristic(props: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=QM6/QM6_spoiler.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_Spoiler_Futuristic.geometry}
        material={materials.main}
        material-color={props.selectedParts.spoiler.color ?? ""}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=QM6/QM6_spoiler.glb");
