/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function SM6_HeadLight_Base(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=SM6/SM6_headlight.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_HeadLight_Base.geometry}
        material={materials.light_glass}
        material-transparent
        material-opacity={0.1}
        material-metalness={0.6}
        material-roughness={0.1}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=SM6/SM6_headlight.glb");
