/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function SM6_Headlight_Offroad_A(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=SM6/SM6_headlight.glb?1") as any;
  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Headlight_Offroad_A_1.geometry}
        material={materials.light_darkmetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Headlight_Offroad_A_2.geometry}
        material={materials.light_led}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Headlight_Offroad_A_3.geometry}
        material={materials.light_matte}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Headlight_Offroad_A_4.geometry}
        material={materials.light_metal}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=SM6/SM6_headlight.glb?1");
