/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group, Mesh } from "three";

export default function XM3_Wheel_Transparent({ ...props }: any) {
  const group = useRef<Group>(null);
  const { nodes, materials } = useGLTF("/api/model-url?name=XM3/XM3_wheel_transparent.glb") as any;

  useEffect(() => {
    return () => {
      Object.values(nodes).forEach(node => {
        // geometry dispose
        if ((node as Mesh).geometry) {
          const mesh = node as Mesh;
          mesh.geometry.dispose();
        }

        // material dispose
        if ((node as Mesh).material) {
          const mesh = node as Mesh;
          const material = mesh.material;

          if (Array.isArray(material)) {
            material.forEach(mat => {
              mat.dispose();
            });
          } else {
            material.dispose();
          }
        }
      });
    };
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_R_1.geometry}
        material={materials.tire_blackmetal}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_R_2.geometry}
        material={materials.tire_brake}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_R_3.geometry}
        material={materials.tire_detail}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_R_4.geometry}
        material={materials.tire_metal}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_R_5.geometry}
        material={materials.tire_rubber}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_L_1.geometry}
        material={materials.tire_blackmetal}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_L_2.geometry}
        material={materials.tire_brake}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_L_3.geometry}
        material={materials.tire_detail}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_L_4.geometry}
        material={materials.tire_metal}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_L_5.geometry}
        material={materials.tire_rubber}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=XM3/XM3_wheel_transparent.glb");
