/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect } from "react";
import { Mesh } from "three";
import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function XM3_Taillamp_Transparent(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=XM3/XM3_taillamp_transparent.glb") as any;

  useEffect(() => {
    return () => {
      Object.values(nodes).forEach(node => {
        // geometry dispose
        if ((node as Mesh).geometry) {
          const mesh = node as Mesh;
          mesh.geometry.dispose();
        }

        // material dispose
        if ((node as Mesh).material) {
          const mesh = node as Mesh;
          const material = mesh.material;

          if (Array.isArray(material)) {
            material.forEach(mat => {
              mat.dispose();
            });
          } else {
            material.dispose();
          }
        }
      });
    };
  }, [nodes]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_TailLamp_BaseParts_1.geometry}
        material={materials.light_led}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_TailLamp_BaseParts_2.geometry}
        material={materials.light_metal}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_TailLamp_BaseParts_3.geometry}
        material={materials.light_redem}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_TailLamp_BaseParts_4.geometry}
        material={materials.tail_glass}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_TailLamp_BaseParts_5.geometry}
        material={materials.taillamp_light}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_TailLamp_BaseParts_6.geometry}
        material={materials.taillamp_red}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=XM3/XM3_taillamp_transparent.glb");
