/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { Mesh } from "three";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function XM3_Bonnet_Transparent({ ...props }: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=XM3/XM3_bonnet_transparent.glb") as any;

  useEffect(() => {
    return () => {
      Object.values(nodes).forEach(node => {
        // geometry dispose
        if ((node as Mesh).geometry) {
          const mesh = node as Mesh;
          mesh.geometry.dispose();
        }

        // material dispose
        if ((node as Mesh).material) {
          const mesh = node as Mesh;
          const material = mesh.material;

          if (Array.isArray(material)) {
            material.forEach(mat => {
              mat.dispose();
            });
          } else {
            material.dispose();
          }
        }
      });
    };
  }, [nodes]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.XM3_Bonnet_BaseParts.geometry}
        material={materials.main}
        material-transparent
        material-opacity={0.3}
        material-color="#fff"
        material-metalness={0.7}
        material-roughness={0.2}
      />
    </group>
  );
}
useGLTF.preload("/api/model-url?name=XM3/XM3_bonnet_transparent.glb");
