/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { Mesh } from "three";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function XM3_Body_Transparent(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=XM3/XM3_body_transparent.glb") as any;

  useEffect(() => {
    return () => {
      Object.values(nodes).forEach(node => {
        // geometry dispose
        if ((node as Mesh).geometry) {
          const mesh = node as Mesh;
          mesh.geometry.dispose();
        }

        // material dispose
        if ((node as Mesh).material) {
          const mesh = node as Mesh;
          const material = mesh.material;

          if (Array.isArray(material)) {
            material.forEach(mat => {
              mat.dispose();
            });
          } else {
            material.dispose();
          }
        }
      });
    };
  }, [nodes]);

  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Body_Base0_1.geometry}
        material={materials.Silver}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Body_Base0_2.geometry}
        material={materials.chrome_black}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Body_Base0_3.geometry}
        material={materials.main}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Body_Base0_4.geometry}
        material={materials.metal}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Body_Base1_1.geometry}
        material={materials.Silver}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Body_Base1_2.geometry}
        material={materials.chrome_black}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Body_Base1_3.geometry}
        material={materials.glass}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Body_Base1_4.geometry}
        material={materials.main}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Body_Base1_5.geometry}
        material={materials.metal}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Body_Base1_6.geometry}
        material={materials.mirror}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Body_Base1_7.geometry}
        material={materials.out_black}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Body_Base1_8.geometry}
        material={materials.plastic_gloss}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Body_Base1_9.geometry}
        material={materials.shade}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=XM3/XM3_body_transparent.glb");
