/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group, Mesh } from "three";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function XM3_Bumper_Transparent({ ...props }: any) {
  const group = useRef<Group>(null);
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=XM3/XM3_bumper_transparent.glb?1") as any;

  useEffect(() => {
    return () => {
      Object.values(nodes).forEach(node => {
        // geometry dispose
        if ((node as Mesh).geometry) {
          const mesh = node as Mesh;
          mesh.geometry.dispose();
        }

        // material dispose
        if ((node as Mesh).material) {
          const mesh = node as Mesh;
          const material = mesh.material;

          if (Array.isArray(material)) {
            material.forEach(mat => {
              mat.dispose();
            });
          } else {
            material.dispose();
          }
        }
      });
    };
  }, [nodes]);

  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_Base_1.geometry}
        material={materials.Silver}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_Base_2.geometry}
        material={materials.main}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_Base_3.geometry}
        material={materials.metal}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_Base_4.geometry}
        material={materials.shade}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_Base_5.geometry}
        material={materials.white}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_BaseParts_1.geometry}
        material={materials.Silver}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_BaseParts_2.geometry}
        material={materials.chrome_black}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_BaseParts_3.geometry}
        material={materials.light_red}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_BaseParts_4.geometry}
        material={materials.metal_matt}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_BaseParts_5.geometry}
        material={materials.out_black}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_BaseParts_6.geometry}
        material={materials.plastic_gloss}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_BaseParts_7.geometry}
        material={materials.shade}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=XM3/XM3_bumper_transparent.glb?1");
