/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function XM3_Bumper_Futuristic_A(props: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=XM3/XM3_bumper_futuristic_A.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_Futuristic_A_1.geometry}
        material={materials.Gold}
        material-metalness={0.4}
        material-roughness={0.15}
      />
      <mesh castShadow receiveShadow geometry={nodes.XM3_Bumper_Futuristic_A_2.geometry} material={materials.Silver} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_Futuristic_A_3.geometry}
        material={materials.chrome_black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_Futuristic_A_4.geometry}
        material={materials.light_led}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_Futuristic_A_5.geometry}
        material={materials.main}
        material-color={props.selectedParts.body.color ?? ""}
        material-metalness={0.05}
        material-roughness={0.15}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Bumper_Futuristic_A_6.geometry}
        material={materials.out_black}
      />
      <mesh castShadow receiveShadow geometry={nodes.XM3_Bumper_Futuristic_A_7.geometry} material={materials.shade} />
      <mesh castShadow receiveShadow geometry={nodes.XM3_Bumper_Futuristic_A_8.geometry} material={materials.white} />
    </group>
  );
}
