/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";
import { useGarageStore } from "@/store/useGarageStore";

export default function XM3_Bumper_Motorsport_B({ ...props }: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=XM3/XM3_bumper_motorsport_B.glb") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group {...props}>
      <mesh geometry={nodes.XM3_Bumper_Motorsport_B_1.geometry} material={materials.Silver} />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_B_2.geometry} material={materials.chrome_black} />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_B_3.geometry} material={materials.light_led} />
      <mesh
        geometry={nodes.XM3_Bumper_Motorsport_B_4.geometry}
        material={materials.main}
        material-color={selectedColors.Bumper}
        material-metalness={0.05}
        material-roughness={0.15}
      />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_B_5.geometry} material={materials.metal_matt} />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_B_6.geometry} material={materials.out_black} />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_B_7.geometry} material={materials.plastic_gloss} />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_B_8.geometry} material={materials.shade} />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_B_9.geometry} material={materials.white} />
    </group>
  );
}
