/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useGarageStore } from "@/store/useGarageStore";

export default function XM3_Bumper_Motorsport_C({ ...props }: any) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/api/model-url?name=XM3/XM3_bumper_motorsport_C.glb") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.XM3_Bumper_Motorsport_C_1.geometry} material={materials.Silver} />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_C_2.geometry} material={materials.chrome_black} />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_C_3.geometry} material={materials.light_led} />
      <mesh
        geometry={nodes.XM3_Bumper_Motorsport_C_4.geometry}
        material={materials.main}
        material-color={selectedColors.Bumper}
        material-metalness={0.05}
        material-roughness={0.15}
      />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_C_5.geometry} material={materials.metal} />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_C_6.geometry} material={materials.metal_matt} />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_C_7.geometry} material={materials.out_black} />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_C_8.geometry} material={materials.plastic_gloss} />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_C_9.geometry} material={materials.shade} />
      <mesh geometry={nodes.XM3_Bumper_Motorsport_C_10.geometry} material={materials.white} />
    </group>
  );
}
