/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function XM3_Bumper_Futuristic_B(props: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=XM3/XM3_bumper_futuristic_B.glb") as any;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.XM3_Bumper_Futuristic_B_1.geometry}
          material={materials.Gold}
          material-metalness={0.4}
          material-roughness={0.15}
        />
        <mesh
          geometry={nodes.XM3_Bumper_Futuristic_B_2.geometry}
          material={materials.main}
          material-color={props.selectedParts.body.color ?? ""}
          material-metalness={0.05}
          material-roughness={0.15}
        />
        <mesh geometry={nodes.XM3_Bumper_Futuristic_B_3.geometry} material={materials.chrome_black} />
        <mesh geometry={nodes.XM3_Bumper_Futuristic_B_4.geometry} material={materials.out_black} />
        <mesh geometry={nodes.XM3_Bumper_Futuristic_B_5.geometry} material={materials.shade} />
        <mesh geometry={nodes.XM3_Bumper_Futuristic_B_6.geometry} material={materials.metal_matt} />
        <mesh geometry={nodes.XM3_Bumper_Futuristic_B_7.geometry} material={materials.light_led} />
        <mesh geometry={nodes.XM3_Bumper_Futuristic_B_8.geometry} material={materials.Silver} />
        <mesh geometry={nodes.XM3_Bumper_Futuristic_B_9.geometry} material={materials.white} />
      </group>
    </group>
  );
}
