/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function XM3_TailLamp_Futuristic_A({ ...props }: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=XM3/XM3_tailLamp_futuristic_A.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.XM3_TailLamp_Futuristic_A_1.geometry}
        material={materials.light_redem}
        material-emissiveIntensity={1.1}
        material-emissive-r={1}
        material-emissive-g={0}
        material-emissive-b={0.04}
        material-color="#ff0000"
      />
      <mesh geometry={nodes.XM3_TailLamp_Futuristic_A_2.geometry} material={materials.taillamp_red} />
    </group>
  );
}
