/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";
import { useGarageStore } from "@/store/useGarageStore";

export default function SM6_Bumper_Motorsport_C({ ...props }: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=SM6/SM6_bumper_motorsport_C.glb") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group {...props}>
      <mesh castShadow receiveShadow geometry={nodes.SM6_Bumper_Motorsport_C_1.geometry} material={materials.Silver} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Bumper_Motorsport_C_2.geometry}
        material={materials.chrome_black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Bumper_Motorsport_C_3.geometry}
        material={materials.light_led}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Bumper_Motorsport_C_4.geometry}
        material={materials.main}
        material-color={selectedColors.Bumper}
        material-metalness={0.05}
        material-roughness={0.15}
      />
      <mesh castShadow receiveShadow geometry={nodes.SM6_Bumper_Motorsport_C_5.geometry} material={materials.metal} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Bumper_Motorsport_C_6.geometry}
        material={materials.out_black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Bumper_Motorsport_C_7.geometry}
        material={materials.plastic_gloss}
      />
      <mesh castShadow receiveShadow geometry={nodes.SM6_Bumper_Motorsport_C_8.geometry} material={materials.shade} />
      <mesh castShadow receiveShadow geometry={nodes.SM6_Bumper_Motorsport_C_9.geometry} material={materials.white} />
    </group>
  );
}
