/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function SM6_Bumper_Offroad_A({ ...props }: any) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/api/model-url?name=SM6/SM6_bumper_offroad_A.glb") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.SM6_Bumper_Offroad_A_1.geometry} material={materials.Leather} />
      <mesh geometry={nodes.SM6_Bumper_Offroad_A_2.geometry} material={materials.Silver} />
      <mesh geometry={nodes.SM6_Bumper_Offroad_A_3.geometry} material={materials.chrome_black} />
      <mesh geometry={nodes.SM6_Bumper_Offroad_A_4.geometry} material={materials.light_led} />
      <mesh
        geometry={nodes.SM6_Bumper_Offroad_A_5.geometry}
        material={materials.main}
        // material-color={props.selectedParts.body.color ?? ""}
        material-metalness={0.05}
        material-roughness={0.15}
      />
      <mesh geometry={nodes.SM6_Bumper_Offroad_A_6.geometry} material={materials.metal} />
      <mesh geometry={nodes.SM6_Bumper_Offroad_A_7.geometry} material={materials.metal_matt} />
      <mesh geometry={nodes.SM6_Bumper_Offroad_A_8.geometry} material={materials.out_black} />
      <mesh geometry={nodes.SM6_Bumper_Offroad_A_9.geometry} material={materials.shade} />
      <mesh geometry={nodes.SM6_Bumper_Offroad_A_10.geometry} material={materials.white} />
    </group>
  );
}
