/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useGarageStore } from "@/store/useGarageStore";

export default function SM6_Bumper_Offroad_B({ ...props }: any) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/api/model-url?name=SM6/SM6_bumper_offroad_B.glb") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.SM6_Bumper_Offroad_B_1.geometry} material={materials.Color_Y} material-color="#ffb700" />
      <mesh geometry={nodes.SM6_Bumper_Offroad_B_2.geometry} material={materials.Silver} />
      <mesh geometry={nodes.SM6_Bumper_Offroad_B_3.geometry} material={materials.chrome_black} />
      <mesh geometry={nodes.SM6_Bumper_Offroad_B_4.geometry} material={materials.light_led} />
      <mesh
        geometry={nodes.SM6_Bumper_Offroad_B_5.geometry}
        material={materials.main}
        material-color={selectedColors.Bumper}
        material-metalness={0.05}
        material-roughness={0.15}
      />
      <mesh geometry={nodes.SM6_Bumper_Offroad_B_6.geometry} material={materials.metal_matt} />
      <mesh geometry={nodes.SM6_Bumper_Offroad_B_7.geometry} material={materials.out_black} />
      <mesh geometry={nodes.SM6_Bumper_Offroad_B_8.geometry} material={materials.shade} />
      <mesh geometry={nodes.SM6_Bumper_Offroad_B_9.geometry} material={materials.white} />
    </group>
  );
}
