/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function QM6_Headlight_Base(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=QM6/QM6_headlight_transparent.glb") as any;
  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_Headlight_Base.geometry}
        material={materials.light_glass}
        material-transparent
        material-opacity={0.1}
        material-metalness={0.6}
        material-roughness={0.1}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=QM6/QM6_headlight_transparent.glb");
