/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useGarageStore } from "@/store/useGarageStore";

export default function XM3_Spoiler_Offroad(props: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=XM3/XM3_spoiler.glb") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.XM3_Spoiler_Offroad_1.geometry} material={materials.Color_R} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Spoiler_Offroad_2.geometry}
        material={materials.main}
        material-color={selectedColors.Spoiler}
      />
      <mesh castShadow receiveShadow geometry={nodes.XM3_Spoiler_Offroad_3.geometry} material={materials.metal} />
      <mesh castShadow receiveShadow geometry={nodes.XM3_Spoiler_Offroad_4.geometry} material={materials.out_black} />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=XM3/XM3_spoiler.glb");
