/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";
import { useGarageStore } from "@/store/useGarageStore";

export default function XM3_Spoiler_Futuristic(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=XM3/XM3_spoiler.glb?1") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Spoiler_Futuristic.geometry}
        material={materials.main}
        material-color={selectedColors.Spoiler}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=XM3/XM3_spoiler.glb?1");
