/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function QM6_TailLamp_Transparent(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=QM6/QM6_tailLamp_transparent.glb") as any;
  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_Taillamp_BaseParts_1.geometry}
        material={materials.light_redem}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_Taillamp_BaseParts_2.geometry}
        material={materials.taillamp_light}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_Taillamp_BaseParts_3.geometry}
        material={materials.taillamp_red}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=QM6/QM6_tailLamp_transparent.glb");
