/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function QM6_Headlight_Transparent(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=QM6/QM6_headlight_transparent.glb") as any;
  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_Headlight_BaseParts_1.geometry}
        material={materials.light_darkmetal}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_Headlight_BaseParts_2.geometry}
        material={materials.light_led}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_Headlight_BaseParts_3.geometry}
        material={materials.light_matte}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_Headlight_BaseParts_4.geometry}
        material={materials.light_metal}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=QM6/QM6_headlight_transparent.glb");
