/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function QM6_Bonnet_Transparent({ ...props }: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=QM6/QM6_bonnet_transparent.glb") as any;
  return (
    <group {...props}>
      <mesh
        geometry={nodes.QM6_Bonnet_BaseParts_1.geometry}
        material={materials.main}
        material-transparent
        material-opacity={0.3}
        material-color="#fff"
        material-metalness={0.7}
        material-roughness={0.2}
      />
      <mesh
        geometry={nodes.QM6_Bonnet_BaseParts_2.geometry}
        material={materials.shade}
        material-transparent
        material-opacity={0.3}
        material-color="#fff"
        material-metalness={0.7}
        material-roughness={0.2}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=QM6/QM6_bonnet_transparent.glb");
