/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";
import { useGarageStore } from "@/store/useGarageStore";

export default function SM6_Bonnet_Futuristic_B({ ...props }: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=SM6/SM6_bonnet_futuristic_B.glb") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.SM6_Bonnet_Futuristic_B_1.geometry}
          material={materials.Gold}
          material-metalness={0.4}
          material-roughness={0.15}
        />
        <mesh
          geometry={nodes.SM6_Bonnet_Futuristic_B_2.geometry}
          material={materials.main}
          material-color={selectedColors.Bonnet}
          material-metalness={0.05}
          material-roughness={0.15}
        />
        <mesh geometry={nodes.SM6_Bonnet_Futuristic_B_3.geometry} material={materials.shade} />
      </group>
    </group>
  );
}
