/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function SM6_Bonnet_Motorsport_C({ ...props }: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=SM6/SM6_bonnet_motorsport_C.glb") as any;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.SM6_Bonnet_Motorsport_C_1.geometry}
          material={materials.main}
          material-color={props.selectedParts.body.color ?? ""}
          material-metalness={0.05}
          material-roughness={0.15}
        />
        <mesh geometry={nodes.SM6_Bonnet_Motorsport_C_2.geometry} material={materials.out_black} />
      </group>
    </group>
  );
}
