/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useGarageStore } from "@/store/useGarageStore";

export default function SM6_Bonnet_Motorsport_A({ ...props }: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=SM6/SM6_bonnet_motorsport_A.glb") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.SM6_Bonnet_Motorsport_A_1.geometry}
          material={materials.main}
          material-color={selectedColors.Bonnet}
          material-metalness={0.05}
          material-roughness={0.15}
        />
        <mesh geometry={nodes.SM6_Bonnet_Motorsport_A_2.geometry} material={materials.out_black} />
      </group>
    </group>
  );
}
