/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function SM6_TailLamp_Base(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=SM6/SM6_tailLamp.glb?1") as any;
  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_TailLamp_Base_1.geometry}
        material={materials.light_metal}
        material-color="red"
        material-transparent
        material-opacity={0.1}
        material-metalness={0.6}
        material-roughness={0.1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_TailLamp_Base_2.geometry}
        material={materials.tail_glass}
        material-color="red"
        material-transparent
        material-opacity={0.1}
        material-metalness={0.6}
        material-roughness={0.1}
      />
    </group>
  );
}
