/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function SM6_TailLamp_Motorsport_C(props: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=SM6/SM6_tailLamp.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_TailLamp_Motorsport_C_1.geometry}
        material={materials.light_redem}
        material-emissiveIntensity={1.1}
        material-emissive-r={1}
        material-emissive-g={0}
        material-emissive-b={0.04}
        material-color="#ff0000"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_TailLamp_Motorsport_C_2.geometry}
        material={materials.taillamp_red}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=SM6/SM6_tailLamp.glb");
