import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "hayoung.dev",
  description: "Generated by Ha young Kim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
