/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";
import { useGarageStore } from "@/store/useGarageStore";

export default function QM6_Bonnet_Motorsport_C({ ...props }: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=QM6/QM6_bonnet_motorsport_C.glb") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.QM6_Bonnet_Motorsport_C_1.geometry}
        material={materials.main}
        material-color={selectedColors.Bonnet}
        material-metalness={0.05}
        material-roughness={0.15}
      />
      <mesh geometry={nodes.QM6_Bonnet_Motorsport_C_2.geometry} material={materials.out_black} />
      <mesh geometry={nodes.QM6_Bonnet_Motorsport_C_3.geometry} material={materials.shade} />
    </group>
  );
}
