/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";
import { useGarageStore } from "@/store/useGarageStore";

export default function QM6_Bonnet_Futuristic_A({ ...props }: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=QM6/QM6_bonnet_futuristic_A.glb?1") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group {...props}>
      <mesh
        geometry={nodes.QM6_Bonnet_Futuristic_A_1.geometry}
        material={materials.main}
        material-color={selectedColors.Bonnet}
        material-metalness={0.05}
        material-roughness={0.15}
      />
      <mesh geometry={nodes.QM6_Bonnet_Futuristic_A_2.geometry} material={materials.plastic_gloss} />
      <mesh geometry={nodes.QM6_Bonnet_Futuristic_A_3.geometry} material={materials.shade} />
    </group>
  );
}
