/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { TextureLoader } from "three";
import { useLoader } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { useGarageStore } from "@/store/useGarageStore";

const QM6_Decal = () => {
  const group = useRef<THREE.Group>(null);
  const { selectedParts } = useGarageStore();
  const patternMeta = selectedParts["Pattern"];

  const { nodes, materials } = useGLTF("/api/model-url?name=QM6/QM6_decal.glb") as any;

  const textures = {
    motorsport: useLoader(TextureLoader, "/api/model-url?name=QM6/QM6_decal_stripe.png"),
    offroad: useLoader(TextureLoader, "/api/model-url?name=QM6/QM6_decal_triangle.png"),
    futuristic: useLoader(TextureLoader, "/api/model-url?name=QM6/QM6_decal_hexagon.png"),
  };

  if (!patternMeta?.theme) return null;

  const map = textures[patternMeta.theme.toLowerCase() as keyof typeof textures];
  if (!map) return null;

  return (
    <group ref={group} dispose={null}>
      <mesh geometry={nodes.QM6_Decal.geometry} material={materials.Decal}>
        <meshStandardMaterial
          attach="material"
          map={map}
          transparent
          metalness={0.4}
          roughness={0.15}
          // color={patternMeta.color ?? undefined}
        />
      </mesh>
    </group>
  );
};

export default QM6_Decal;
