/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function XM3_Headlight_Motorsport_C(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=XM3/XM3_headlight.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Headlight_Motorsport_C_1.geometry}
        material={materials.light_darkmetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Headlight_Motorsport_C_2.geometry}
        material={materials.light_led}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Headlight_Motorsport_C_3.geometry}
        material={materials.light_matte}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Headlight_Motorsport_C_4.geometry}
        material={materials.light_metal}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=XM3/XM3_headlight.glb");
