/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function XM3_Headlight_Motorsport_A(props: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=XM3/XM3_headlight.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Headlight_Motorsport_A__1.geometry}
        material={materials.light_darkmetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Headlight_Motorsport_A__2.geometry}
        material={materials.light_led}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Headlight_Motorsport_A__3.geometry}
        material={materials.light_matte}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Headlight_Motorsport_A__4.geometry}
        material={materials.light_metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Headlight_Motorsport_A__5.geometry}
        material={materials.main}
        material-color={props.selectedParts.body.color ?? ""}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=XM3/XM3_headlight.glb");
