/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";
import { useGarageStore } from "@/store/useGarageStore";

export default function XM3_Headlight_Motorsport_A(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=XM3/XM3_headlight.glb?1") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Headlight_Motorsport_A__1.geometry}
        material={materials.light_darkmetal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Headlight_Motorsport_A__2.geometry}
        material={materials.light_led}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Headlight_Motorsport_A__3.geometry}
        material={materials.light_matte}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Headlight_Motorsport_A__4.geometry}
        material={materials.light_metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Headlight_Motorsport_A__5.geometry}
        material={materials.main}
        material-color={selectedColors.Body}
      />
    </group>
  );
}
