/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function XM3_Roofcarrier_Futuristic(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=XM3/XM3_roofcarrier.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Roofcarrier_Futuristic_1.geometry}
        material={materials.light_led}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Roofcarrier_Futuristic_2.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Roofcarrier_Futuristic_3.geometry}
        material={materials.out_black}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=XM3/XM3_roofcarrier.glb");
