/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function XM3_Roofcarrier_Offroad(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=XM3/XM3_roofcarrier.glb?1") as any;
  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Roofcarrier_Offroad__1.geometry}
        material={materials.light_led}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Roofcarrier_Offroad__2.geometry}
        material={materials.out_black}
      />
      <mesh castShadow receiveShadow geometry={nodes.XM3_Roofcarrier_Offroad__3.geometry} material={materials.shade} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Roofcarrier_Offroad__4.geometry}
        material={materials.tire_rubber}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=XM3/XM3_roofcarrier.glb?1");
