/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useGarageStore } from "@/store/useGarageStore";

export default function SM6_Spoiler_Futuristic(props: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=SM6/SM6_spoiler.glb") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Spoiler_Futuristic.geometry}
        material={materials.main}
        material-color={selectedColors.Spoiler}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=SM6/SM6_spoiler.glb");
