/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function SM6_Spoiler_Motorsport(props: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=SM6/SM6_spoiler.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.SM6_Spoiler_Motorsport_1.geometry} material={materials.Color_Y} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Spoiler_Motorsport_2.geometry}
        material={materials.main}
        // material-color={props.selectedParts.spoiler.color ?? ""}
      />
      <mesh castShadow receiveShadow geometry={nodes.SM6_Spoiler_Motorsport_3.geometry} material={materials.metal} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Spoiler_Motorsport_4.geometry}
        material={materials.out_black}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=SM6/SM6_spoiler.glb");
