/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function QM6_Bumper_Motorsport_B({ ...props }: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=QM6/QM6_bumper_motorsport_B.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.QM6_Bumper_Motorsport_B_1.geometry} material={materials.chrome_black} />
      <mesh geometry={nodes.QM6_Bumper_Motorsport_B_2.geometry} material={materials.light_led} />
      <mesh
        geometry={nodes.QM6_Bumper_Motorsport_B_3.geometry}
        material={materials.main}
        // material-color={props.selectedParts.body.color ?? ""}
        material-metalness={0.05}
        material-roughness={0.15}
      />
      <mesh geometry={nodes.QM6_Bumper_Motorsport_B_4.geometry} material={materials.metal} />
      <mesh geometry={nodes.QM6_Bumper_Motorsport_B_5.geometry} material={materials.metal_matt} />
      <mesh geometry={nodes.QM6_Bumper_Motorsport_B_6.geometry} material={materials.out_black} />
      <mesh geometry={nodes.QM6_Bumper_Motorsport_B_7.geometry} material={materials.shade} />
      <mesh geometry={nodes.QM6_Bumper_Motorsport_B_8.geometry} material={materials.white} />
    </group>
  );
}
