/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";
import { useGarageStore } from "@/store/useGarageStore";

export default function QM6_Bumper_Futuristic_B({ ...props }: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=QM6/QM6_bumper_futuristic_B.glb") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.QM6_Bumper_Futuristic_B_1.geometry}
          material={materials.Gold}
          material-metalness={0.4}
          material-roughness={0.15}
        />
        <mesh
          geometry={nodes.QM6_Bumper_Futuristic_B_2.geometry}
          material={materials.main}
          material-color={selectedColors.Bumper}
          material-metalness={0.05}
          material-roughness={0.15}
        />
        <mesh geometry={nodes.QM6_Bumper_Futuristic_B_3.geometry} material={materials.chrome_black} />
        <mesh geometry={nodes.QM6_Bumper_Futuristic_B_4.geometry} material={materials.shade} />
        <mesh geometry={nodes.QM6_Bumper_Futuristic_B_5.geometry} material={materials.light_led} />
        <mesh geometry={nodes.QM6_Bumper_Futuristic_B_6.geometry} material={materials.Silver} />
        <mesh geometry={nodes.QM6_Bumper_Futuristic_B_7.geometry} material={materials.white} />
      </group>
    </group>
  );
}
