/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function XM3_Bonnet_Futuristic_A({ ...props }: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=XM3/XM3_bonnet_futuristic_A.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.XM3_Bonnet_Futuristic_A_1.geometry}
        material={materials.main}
        // material-color={props.selectedParts.body.color ?? ""}
        material-metalness={0.05}
        material-roughness={0.15}
      />
      <mesh geometry={nodes.XM3_Bonnet_Futuristic_A_2.geometry} material={materials.plastic_gloss} />
    </group>
  );
}
