/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";
import { useGarageStore } from "@/store/useGarageStore";

export default function XM3_Bonnet_Motorsport_B({ ...props }: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=XM3/XM3_bonnet_motorsport_B.glb") as any;
  const { selectedColors } = useGarageStore();
  return (
    <group {...props}>
      <mesh
        geometry={nodes.XM3_Bonnet_Motorsport_B_1.geometry}
        material={materials.main}
        material-color={selectedColors.Bonnet}
        material-metalness={0.05}
        material-roughness={0.15}
      />
      <mesh geometry={nodes.XM3_Bonnet_Motorsport_B_2.geometry} material={materials.out_black} />
    </group>
  );
}
