/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function SM6_Roofcarrier_Offroad(props: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=SM6/SM6_roofcarrier.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Roofcarrier_Offroad_1.geometry}
        material={materials.light_led}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Roofcarrier_Offroad_2.geometry}
        material={materials.out_black}
      />
      <mesh castShadow receiveShadow geometry={nodes.SM6_Roofcarrier_Offroad_3.geometry} material={materials.shade} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Roofcarrier_Offroad_4.geometry}
        material={materials.tire_rubber}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=SM6/SM6_roofcarrier.glb");
