/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=QM6/QM6_roofcarrier.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_Roofcarrier_Futuristic_1.geometry}
        material={materials.light_led}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_Roofcarrier_Futuristic_2.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_Roofcarrier_Futuristic_3.geometry}
        material={materials.out_black}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=QM6/QM6_roofcarrier.glb");
