/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function SM6_TailLamp_Transparent(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=SM6/SM6_tailLamp_transparent.glb?1") as any;
  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_TailLamp_BaseParts_1.geometry}
        material={materials.light_metal}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_TailLamp_BaseParts_2.geometry}
        material={materials.light_redem}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_TailLamp_BaseParts_3.geometry}
        material={materials.taillamp_light}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_TailLamp_BaseParts_4.geometry}
        material={materials.taillamp_red}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=SM6/SM6_tailLamp_transparent.glb?1");
