/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function SM6_Bonnet_Transparent({ ...props }: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=SM6/SM6_bonnet_transparent.glb") as any;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.SM6_Bonnet_BaseParts_1.geometry}
          material={materials.main}
          material-transparent
          material-opacity={0.3}
          material-color="#fff"
          material-metalness={0.7}
          material-roughness={0.2}
        />
        <mesh
          geometry={nodes.SM6_Bonnet_BaseParts_2.geometry}
          material={materials.shade}
          material-transparent
          material-opacity={0.3}
          material-color="#fff"
          material-metalness={0.7}
          material-roughness={0.2}
        />
      </group>
    </group>
  );
}
useGLTF.preload("/api/model-url?name=SM6/SM6_bonnet_transparent.glb");
