/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function SM6_Wheel_Transparent({ ...props }: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=SM6/SM6_wheel_transparent.glb?1") as any;
  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Wheel_BaseParts_R_1.geometry}
        material={materials.tire_blackmetal}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Wheel_BaseParts_R_2.geometry}
        material={materials.tire_brake}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Wheel_BaseParts_R_3.geometry}
        material={materials.tire_detail}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Wheel_BaseParts_R_4.geometry}
        material={materials.tire_metal}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Wheel_BaseParts_R_5.geometry}
        material={materials.tire_rubber}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Wheel_BaseParts_L_1.geometry}
        material={materials.tire_blackmetal}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Wheel_BaseParts_L_2.geometry}
        material={materials.tire_brake}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Wheel_BaseParts_L_3.geometry}
        material={materials.tire_detail}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Wheel_BaseParts_L_4.geometry}
        material={materials.tire_metal}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Wheel_BaseParts_L_5.geometry}
        material={materials.tire_rubber}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=SM6/SM6_wheel_transparent.glb?1");
