/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function SM6_Headlight_Transparent(props: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=SM6/SM6_headlight_transparent.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Headlight_BaseParts_1.geometry}
        material={materials.light_darkmetal}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Headlight_BaseParts_2.geometry}
        material={materials.light_led}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Headlight_BaseParts_3.geometry}
        material={materials.light_matte}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SM6_Headlight_BaseParts_4.geometry}
        material={materials.light_metal}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=SM6/SM6_headlight_transparent.glb");
