/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

export default function Model(props: any) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=QM6/QM6_tailLamp.glb") as any;
  return (
    <group {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_TailLamp_Motorsport_A_1.geometry}
        material={materials.light_redem}
        material-emissiveIntensity={1.1}
        material-emissive-r={1}
        material-emissive-g={0}
        material-emissive-b={0.04}
        material-color="#ff0000"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QM6_TailLamp_Motorsport_A_2.geometry}
        material={materials.taillamp_red}
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=QM6/QM6_tailLamp.glb");
