/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { getWheelXOffset } from "@/utils/garage";
import { WheelProps } from "@/types/garage";

export default function XM3_Wheel_Motorsport_A({ carType, bumperMeta }: WheelProps) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/api/model-url?name=XM3/XM3_wheel_motorsport_A.glb") as any;

  const leftPos = getWheelXOffset({
    carType,
    bumperTheme: bumperMeta?.theme,
    bumperVariant: bumperMeta?.variant,
    side: "left",
  });

  const rightPos = getWheelXOffset({
    carType,
    bumperTheme: bumperMeta?.theme,
    bumperVariant: bumperMeta?.variant,
    side: "right",
  });

  return (
    <group ref={group} dispose={null}>
      <group position={rightPos}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XM3_Wheel_Motorsport_A_R_1.geometry}
          material={materials.metal_matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XM3_Wheel_Motorsport_A_R_2.geometry}
          material={materials.tire_blackmetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XM3_Wheel_Motorsport_A_R_3.geometry}
          material={materials.tire_brake}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XM3_Wheel_Motorsport_A_R_4.geometry}
          material={materials.tire_detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XM3_Wheel_Motorsport_A_R_5.geometry}
          material={materials.tire_metal}
          // material-color={props.selectedParts.wheel.color ?? ""}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XM3_Wheel_Motorsport_A_R_6.geometry}
          material={materials.tire_rubber}
        />
      </group>

      <group position={leftPos}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XM3_Wheel_Motorsport_A_L_1.geometry}
          material={materials.metal_matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XM3_Wheel_Motorsport_A_L_2.geometry}
          material={materials.tire_blackmetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XM3_Wheel_Motorsport_A_L_3.geometry}
          material={materials.tire_brake}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XM3_Wheel_Motorsport_A_L_4.geometry}
          material={materials.tire_detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XM3_Wheel_Motorsport_A_L_5.geometry}
          material={materials.tire_metal}
          // material-color={props.selectedParts.wheel.color ?? ""}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.XM3_Wheel_Motorsport_A_L_6.geometry}
          material={materials.tire_rubber}
        />
      </group>
    </group>
  );
}
