/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { TextureLoader } from "three";
import { useLoader } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }: any) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/api/model-url?name=XM3/XM3_decal.glb") as any;

  const pattern_motorsport = useLoader(TextureLoader, "/api/model-url?name=XM3/XM3_decal_stripe.png");
  const pattern_offroad = useLoader(TextureLoader, "/api/model-url?name=XM3/XM3_decal_triangle.png");
  const pattern_futuristic = useLoader(TextureLoader, "/api/model-url?name=XM3/XM3_decal_hexagon.png");

  return (
    <group ref={group} {...props} dispose={null}>
      {props.selectedParts.pattern.id === "901" ? (
        <mesh geometry={nodes.XM3_Decal.geometry} material={materials.Decal}>
          <meshStandardMaterial
            attach="material"
            map={pattern_motorsport}
            transparent
            metalness={0.4}
            roughness={0.15}
            color={props.selectedParts.pattern.color}
          />
        </mesh>
      ) : props.selectedParts.pattern.id === "902" ? (
        <mesh geometry={nodes.XM3_Decal.geometry} material={materials.Decal}>
          <meshStandardMaterial
            attach="material"
            map={pattern_offroad}
            transparent
            metalness={0.4}
            roughness={0.15}
            color={props.selectedParts.pattern.color}
          />
        </mesh>
      ) : props.selectedParts.pattern.id === "903" ? (
        <mesh geometry={nodes.XM3_Decal.geometry} material={materials.Decal}>
          <meshStandardMaterial
            attach="material"
            map={pattern_futuristic}
            transparent
            metalness={0.4}
            roughness={0.15}
            color={props.selectedParts.pattern.color}
          />
        </mesh>
      ) : null}
    </group>
  );
}
