/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function XM3_wheel_transparent({ ...props }: any) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/models/XM3/XM3_wheel_transparent.glb") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_R_1.geometry}
        material={materials.tire_blackmetal}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_R_2.geometry}
        material={materials.tire_brake}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_R_3.geometry}
        material={materials.tire_detail}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_R_4.geometry}
        material={materials.tire_metal}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_R_5.geometry}
        material={materials.tire_rubber}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_L_1.geometry}
        material={materials.tire_blackmetal}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_L_2.geometry}
        material={materials.tire_brake}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_L_3.geometry}
        material={materials.tire_detail}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_L_4.geometry}
        material={materials.tire_metal}
        material-transparent
        material-opacity={0.45}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_Wheel_BaseParts_L_5.geometry}
        material={materials.tire_rubber}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
    </group>
  );
}

useGLTF.preload("/models/XM3/XM3_wheel_transparent.glb");
