/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }: any) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/api/model-url?name=XM3/XM3_body.glb") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.XM3_Body_Base1_1.geometry} material={materials.Silver} />
      <mesh geometry={nodes.XM3_Body_Base1_2.geometry} material={materials.chrome_black} />
      <mesh geometry={nodes.XM3_Body_Base1_3.geometry} material={materials.glass} />
      <mesh geometry={nodes.XM3_Body_Base1_4.geometry} material={materials.metal} />
      <mesh geometry={nodes.XM3_Body_Base1_5.geometry} material={materials.mirror} />
      <mesh geometry={nodes.XM3_Body_Base1_6.geometry} material={materials.out_black} />
      <mesh geometry={nodes.XM3_Body_Base1_7.geometry} material={materials.plastic_gloss} />
      <mesh geometry={nodes.XM3_Body_Base1_8.geometry} material={materials.shade} />
      <mesh geometry={nodes.XM3_Body_Base0_1.geometry} material={materials.Silver} />
      <mesh geometry={nodes.XM3_Body_Base0_2.geometry} material={materials.chrome_black} />
      <mesh
        geometry={nodes.XM3_Body_Base0_3.geometry}
        material={materials.main}
        // material-color={props.selectedParts.body.color ?? ""}
        material-metalness={0.05}
        material-roughness={0.15}
      />
      <mesh geometry={nodes.XM3_Body_Base0_4.geometry} material={materials.metal} />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=XM3/XM3_body.glb");
