/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function XM3_taillamp_transparent(props: any) {
  const { nodes, materials } = useGLTF("/api/model-url?name=XM3/XM3_taillamp_transparent.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_TailLamp_BaseParts_1.geometry}
        material={materials.light_led}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_TailLamp_BaseParts_2.geometry}
        material={materials.light_metal}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_TailLamp_BaseParts_3.geometry}
        material={materials.light_redem}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_TailLamp_BaseParts_4.geometry}
        material={materials.tail_glass}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_TailLamp_BaseParts_5.geometry}
        material={materials.taillamp_light}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XM3_TailLamp_BaseParts_6.geometry}
        material={materials.taillamp_red}
        material-transparent
        material-opacity={0.2}
        material-color="#fff"
      />
    </group>
  );
}

useGLTF.preload("/api/model-url?name=XM3/XM3_taillamp_transparent.glb");
