/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { TextureLoader } from "three";
import { useLoader } from "@react-three/fiber";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";
import { useGarageStore } from "@/store/useGarageStore";

const XM3_Decal = () => {
  const { selectedParts, selectedColors } = useGarageStore();
  const patternMeta = selectedParts["Pattern"];

  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=XM3/XM3_decal.glb?1") as any;

  const textures = {
    motorsport: useLoader(TextureLoader, "/api/model-url?name=XM3/XM3_decal_stripe.png"),
    offroad: useLoader(TextureLoader, "/api/model-url?name=XM3/XM3_decal_triangle.png"),
    futuristic: useLoader(TextureLoader, "/api/model-url?name=XM3/XM3_decal_hexagon.png"),
  };

  if (!patternMeta?.theme) return null;

  const map = textures[patternMeta.theme.toLowerCase() as keyof typeof textures];
  if (!map) return null;

  return (
    <group>
      <mesh geometry={nodes.XM3_Decal.geometry} material={materials.Decal}>
        <meshStandardMaterial
          attach="material"
          map={map}
          transparent
          metalness={0.4}
          roughness={0.15}
          color={selectedColors.Pattern}
        />
      </mesh>
    </group>
  );
};

export default XM3_Decal;
