/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";
import { getWheelXOffset } from "@/utils/garage";
import { WheelProps } from "@/types/garage";
import { useGarageStore } from "@/store/useGarageStore";

export default function Model({ carType, bumperMeta }: WheelProps) {
  const { nodes, materials } = useGLTFWithDispose("/api/model-url?name=QM6/QM6_wheel_offroad_B.glb") as any;
  const { selectedColors } = useGarageStore();

  const leftPos = getWheelXOffset({
    carType,
    bumperTheme: bumperMeta?.theme,
    bumperVariant: bumperMeta?.variant,
    side: "left",
  });

  const rightPos = getWheelXOffset({
    carType,
    bumperTheme: bumperMeta?.theme,
    bumperVariant: bumperMeta?.variant,
    side: "right",
  });

  return (
    <group>
      <group position={leftPos}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Offroad_B_L_1.geometry}
          material={materials.Wheel_disk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Offroad_B_L_2.geometry}
          material={materials.metal_matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Offroad_B_L_3.geometry}
          material={materials.tire_blackmetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Offroad_B_L_4.geometry}
          material={materials.tire_brake}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Offroad_B_L_5.geometry}
          material={materials.tire_detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Offroad_B_L_6.geometry}
          material={materials.tire_metal}
          material-color={selectedColors.Wheel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Offroad_B_L_7.geometry}
          material={materials.tire_rubber}
        />
      </group>

      <group position={rightPos}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Offroad_B_R_1.geometry}
          material={materials.Wheel_disk}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Offroad_B_R_2.geometry}
          material={materials.metal_matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Offroad_B_R_3.geometry}
          material={materials.tire_blackmetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Offroad_B_R_4.geometry}
          material={materials.tire_brake}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Offroad_B_R_5.geometry}
          material={materials.tire_detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Offroad_B_R_6.geometry}
          material={materials.tire_metal}
          material-color={selectedColors.Wheel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Offroad_B_R_7.geometry}
          material={materials.tire_rubber}
        />
      </group>
    </group>
  );
}
