/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }: any) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF("/api/model-url?name=QM6/QM6_wheel_futuristic_B.glb") as any;
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={
          props.selectedParts.bumper.id === "301"
            ? [0, 0, -40]
            : props.selectedParts.bumper.id === "302"
            ? [0, 0, -105]
            : props.selectedParts.bumper.id === "303"
            ? [0, 0, -105]
            : props.selectedParts.bumper.id === "304"
            ? [0, 0, -100]
            : props.selectedParts.bumper.id === "305"
            ? [0, 0, -60]
            : props.selectedParts.bumper.id === "306"
            ? [0, 0, -50]
            : props.selectedParts.bumper.id === "307"
            ? [0, 0, -40]
            : [0, 0, 0]
        }
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Futuristic_B_L_1.geometry}
          material={materials.metal_matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Futuristic_B_L_2.geometry}
          material={materials.tire_detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Futuristic_B_L_3.geometry}
          material={materials.tire_metal}
          material-color={props.selectedParts.wheel.color ?? ""}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Futuristic_B_L_4.geometry}
          material={materials.tire_rubber}
        />
      </group>

      <group
        position={
          props.selectedParts.bumper.id === "301"
            ? [0, 0, 40]
            : props.selectedParts.bumper.id === "302"
            ? [0, 0, 105]
            : props.selectedParts.bumper.id === "303"
            ? [0, 0, 105]
            : props.selectedParts.bumper.id === "304"
            ? [0, 0, 100]
            : props.selectedParts.bumper.id === "305"
            ? [0, 0, 60]
            : props.selectedParts.bumper.id === "306"
            ? [0, 0, 50]
            : props.selectedParts.bumper.id === "307"
            ? [0, 0, 40]
            : [0, 0, 0]
        }
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Futuristic_B_R_1.geometry}
          material={materials.metal_matt}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Futuristic_B_R_2.geometry}
          material={materials.tire_detail}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Futuristic_B_R_3.geometry}
          material={materials.tire_metal}
          material-color={props.selectedParts.wheel.color ?? ""}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.QM6_Wheel_Futuristic_B_R_4.geometry}
          material={materials.tire_rubber}
        />
      </group>
    </group>
  );
}
