/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\assets\models\modern_garage_4k.glb -t -i -E -k 
Files: .\public\assets\models\modern_garage_4k.glb [6.67MB] > C:\hayoung\study\hayfolio\modern_garage_4k-transformed.glb [29.4KB] (100%)
Author: Gary J.A. Lowell (https://sketchfab.com/dogtorque)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/modern-garage-8a34c73da7914676b342a3a8782c4796
Title: Modern Garage
*/

import React, { JSX } from "react";
import { Mesh, MeshPhysicalMaterial, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";
import { useGLTF } from "@react-three/drei";
import { useGLTFWithDispose } from "@/hooks/useGLTFWithDispose";

type GLTFResult = GLTF & {
  nodes: {
    Modern_Garage_0: Mesh;
    Modern_Garage_Light_0: Mesh;
  };
  materials: {
    Basic_White: MeshPhysicalMaterial;
    Basic_White_Light: MeshStandardMaterial;
  };
};

export default function Modern_garage_4k(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTFWithDispose("/assets/models/modern_garage_4k.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Modern_Garage_0"
        geometry={nodes.Modern_Garage_0.geometry}
        material={materials.Basic_White}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Modern_Garage_Light_0"
        geometry={nodes.Modern_Garage_Light_0.geometry}
        material={materials.Basic_White_Light}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/assets/models/modern_garage_4k.glb");
